- name: Run using a project directory
  hosts: all
  remote_user: ansible
  gather_facts: no
  vars_files:
    - credentials.yml
  tasks:
    - name: Create ENV variables
      environment:
        MYSQL_DATABASE: "{{ mysql.database }}"
        MYSQL_ROOT_PASSWORD: "{{ mysql.root_password }}"
        MYSQL_USER: "{{ mysql.user }}"
        MYSQL_PASSWORD: "{{ mysql.password }}"

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: .

    - name: Login to docker hub
      docker_login:
        username: "{{ docker.username }}"
        password: "{{ docker.password }}"
    - name: Try docker-compose
      command: docker-compose up -d
      register: result
    
    - debug:
        var: result
