---
- hosts: all
  vars_files:
    - vault.yml
  vars:
    ansible_become_pass: "{{ password }}"
  remote_user: logikdev
  become: true
  tasks:
  - name: Install Packages
    apt:
      pkg:
      - docker
      - docker-compose
  - name: Start Docker Service
    service:
      name: docker
      state: started
  - name: Add User "{{ user }}" to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes
