- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"

  tasks:

  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }}, `dig +short {{ item }}`"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_hosts_results

  - name: Add/Update the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_hosts_results.results }}" 
  
