version: '3'
services:
  spring:
    image: logikdevfr/spring:latest
    container_name: spring
    ports:
      - 80:8080
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /srv/volumes/db-data:/var/lib/mysql
volumes:
  db-data:
