- name: Run using a project directory
  hosts: all
  remote_user: "{{ vars[inventory_hostname].user.name }}"
  gather_facts: no

  vars_files:
    - ../credentials.yml

  tasks:
    

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: .

    - name: Login to docker hub
      docker_login:
        username: "{{ docker.username }}"
        password: "{{ docker.password }}"

    - name: Stop running containers
      command: docker-compose down

    - name: Remove containers
      command: docker-compose rm

    - name: Docker pull
      command: docker-compose pull
      environment:
        MYSQL_DATABASE: "{{ mysql.database }}"
        MYSQL_ROOT_PASSWORD: "{{ mysql.root_password }}"
        MYSQL_USER: "{{ mysql.user }}"
        MYSQL_PASSWORD: "{{ mysql.password }}"

    - name: Start Services
      command: docker-compose up -d 
